### ISSUE TITLE
(machine) Status isn't updated correctly on relation broken

### ISSUE THREAD

**Issue by sed-i** [canonical/grafana-agent-k8s-operator#164]
If we have all the mandatory relations in place, and then remove one of them, the status will still show "Active".

This is because on relation-broken, the relation that is going away is [still present](https://github.com/canonical/operator/issues/888) in `self.model.relations`:

https://github.com/canonical/grafana-agent-k8s-operator/blob/db550c6ead28954c8863652cb465dc85784e0f6b/src/grafana_agent.py#L325-L325

**Comment by Abuelodelanada** [comment]
@sed-i when you said:

> If we have all the mandatory relations in place

Do you mean these ones?

```yaml
  send-remote-write:
    interface: prometheus_remote_write
  logging-consumer:
    interface: loki_push_api
  grafana-cloud-config:
    interface: grafana_cloud_config
    limit: 1

```
