### ISSUE TITLE
Use pyproject.toml instead of requirements.txt?

### ISSUE THREAD

**Issue by sed-i** [canonical/grafana-agent-k8s-operator#165]
> turns out if you use pyproject.toml you don't quite need dependencies.txt. So yeah, we should drop that and unify.

```toml
[project]
name = "grafana-agent-k8s-operator"
# FIXME: Packing the charm with 2.2.0+139.gd011d92 will not include dependencies in PYDEPS key:
# https://chat.charmhub.io/charmhub/pl/wngp665ycjnb78ar9ojrfhxjkr
# That's why we are including cosl here until the bug in charmcraft is solved
dependencies = [
    "cosl",
    "ops>=2.0",
    "pydantic",
    "requests",
    "kubernetes",
    "lightkube",
    "lightkube-models",
]
version = "0.1"

# required for tox to work with isolated_build
[build-system]
requires = [
    "setuptools >= 35.0.2",
    "setuptools_scm >= 2.0.0, <3"
]

build-backend = "setuptools.build_meta"
```

_Originally posted by @PietroPasotti in https://github.com/canonical/grafana-agent-k8s-operator/pull/160#discussion_r1157463376_
