### ISSUE TITLE
timex metrics variables not useful for operations

### ISSUE THREAD

**Issue by gabrielcocenza** [canonical/grafana-agent-k8s-operator#199]
### Bug Description

I've been taking a look on the metrics generated by the node exporter regarding timex (NTP) and some interesting issues were discovered:

1. `node_timex_offset_seconds` is always zero. This is a known [0](https://bugzilla.redhat.com/show_bug.cgi?id=1791875) ][1](https://github.com/prometheus/node_exporter/issues/2445)  issue where the response of the kernel for offset is always zero.
 
![image](https://github.com/canonical/grafana-agent-k8s-operator/assets/23260991/c04cffd0-0681-4a36-9a78-ef6518101aa5)

2. After finding this issue, my next step was check if `node_timex_sync_status` was reliable. For that I've tried the following approaches:

- Stopping the chronyd service. The exporter still give result as `1` (sync working)
- Adding a nonexistent pool on `/etc/chrony/chrony.conf`. The exporter still give result as `1` (sync working)
- Removing all pools. The exporter gave resul `0` (sync not working)

If we can't rely on those metric to create alerts, I guess it doesn't make sense to export it and have on our grafana dashboards.

### To Reproduce

Deploy COS light on one bundle.

Deploy this bundle on another model:

```yaml
saas:
  grafana-dashboards:
    url: serverstack-serverstack:admin/cos.grafana-dashboards
  loki-logging:
    url: serverstack-serverstack:admin/cos.loki-logging
  prometheus-receive-remote-write:
    url: serverstack-serverstack:admin/cos.prometheus-receive-remote-write
  prometheus-scrape:
    url: serverstack-serverstack:admin/cos.prometheus-scrape
applications:
  grafana-agent:
    charm: grafana-agent
    channel: edge
    revision: 9
    series: jammy
  ntp:
    charm: ntp
    channel: stable
    revision: 50
    series: focal
  ubuntu:
    charm: ubuntu
    channel: stable
    revision: 22
    series: focal
    num_units: 2
    to:
    - "0"
    - "2"
    constraints: arch=amd64
    storage:
      block: loop,100M
      files: rootfs,1,100M
machines:
  "0":
    constraints: arch=amd64
    series: focal
  "2":
    constraints: arch=amd64
    series: focal
relations:
- - grafana-agent:juju-info
  - ubuntu:juju-info
- - ntp:juju-info
  - ubuntu:juju-info
- - grafana-agent:logging-consumer
  - loki-logging:logging
- - grafana-agent:send-remote-write
  - prometheus-receive-remote-write:receive-remote-write
- - grafana-agent:grafana-dashboards-provider
  - grafana-dashboards:grafana-dashboard
```

After that it's just accessing the cos-catalogue for grafana and prometheus

### Environment

Running on serverstack using focal series for the Ubuntu charms.

### Relevant log output

```shell
There are no useful logs in this case.
```
