### ISSUE TITLE
[machine] split the `runs-on` into separate sections

### ISSUE THREAD

**Issue by sed-i** [canonical/grafana-agent-k8s-operator#243]
### Enhancement Proposal

For subordinate charms it makes sense to be able to run on multiple series.

Currently, we `build-on` 22.04, and use that same build to run on 22.04 and 20.04.
```yaml
# produces one charm file, grafana-agent_ubuntu-22.04-amd64_ubuntu-20.04-amd64.charm
bases:
  - build-on:
    - name: "ubuntu"
      channel: "22.04"
    run-on:
    - name: "ubuntu"
      channel: "22.04"
    - name: "ubuntu"
      channel: "20.04"
```
This could cause problems (py310 vs py38).

We should probably split it into separate sections:
```yaml
# would produce two charm files
bases:
  - build-on:
    - name: "ubuntu"
      channel: "22.04"
    run-on:
    - name: "ubuntu"
      channel: "22.04"
  - build-on:
    - name: "ubuntu"
      channel: "20.04"
    run-on:
    - name: "ubuntu"
      channel: "20.04"
```

See also:
- https://discourse.charmhub.io/t/charmcraft-bases-provider-support/4713
