### ISSUE TITLE
Severity "high" is not valid

### ISSUE THREAD

**Issue by mcarvalhor** [canonical/grafana-agent-k8s-operator#359]
### Bug Description

Hi!

I am getting this error on AlertManager pod logs:
```
2025-03-14T14:43:36.703Z [alertmanager] ts=2025-03-14T14:43:36.703Z caller=dispatch.go:353 level=error component=dispatcher msg="Notify for alerts failed" num_alerts=2 err="pagerduty/pagerduty[0]: notify retry canceled due to unrecoverable error after 1 attempts: unexpected status code 400: Event object is invalid: 'payload.severity' is invalid (must be one of the following: 'critical', 'warning', 'error' or 'info')"
```

I believe this is because of this:
- https://github.com/canonical/grafana-agent-k8s-operator/blob/5ddeb41e187d2025dda4159561c0e3f31882b04b/src/loki_alert_rules/grafana_agent_high_rate.rule#L8

Severity "high" is not valid, I believe this should be set to "critical" or "warning" instead.
This is not affecting other alerts or COS overall functionality.

### To Reproduce

1. Deploy COS
2. Relate grafana-agent
3. Get the alert on Alertmanager
4. See the error on Alertmanager pod logs

### Environment

Production IS COS

### Relevant log output

```shell
2025-03-14T14:43:36.703Z [alertmanager] ts=2025-03-14T14:43:36.703Z caller=dispatch.go:353 level=error component=dispatcher msg="Notify for alerts failed" num_alerts=2 err="pagerduty/pagerduty[0]: notify retry canceled due to unrecoverable error after 1 attempts: unexpected status code 400: Event object is invalid: 'payload.severity' is invalid (must be one of the following: 'critical', 'warning', 'error' or 'info')"
```

**Comment by marcusboden** [comment]
As a workaround, we use this go-template in our alertmanager configuration:
```yaml
receivers:
- name: dummy
- name: pagerduty
  pagerduty_configs:
  - routing_key: <routing key>
    client_url: http://<traefik-external-ip>/cos-alertmanager
    severity: '{{ $sev := (index .Alerts 0).Labels.severity }}{{ if eq $sev "critical" "warning" "error" }}{{$sev}}{{ else }}warning{{ end }}'
```
This sets the severity to "warning" if the severity wasn't an acceptable value for PD.
