### ISSUE TITLE
Upgrade Grafana Agent OCI image

### ISSUE THREAD

**Issue by Abuelodelanada** [canonical/grafana-agent-k8s-operator#63]
### Enhancement Proposal

In metadata.yaml we have:

```yaml
resources:
  agent-image:
    type: oci-image
    upstream-source: grafana/agent:v0.26.1
    description: OCI image for Grafana Agent
```

But the last Grafana agent version is [`0.28.0`](https://github.com/grafana/agent/releases/tag/v0.28.0)
